import scanpy as sc
import pandas as pd
import celltypist
import argparse
import textwrap
# from celltypist import models
# from pyprojroot.here import here

def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, 
        description=textwrap.dedent('''\
            Annotate h5ad via Celltypist. For list of available models, see website: https://www.celltypist.org/

            Models available at time of writing:
            0	Immune_All_Low	                        immune sub-populations combined from 20 tissue...
            1	Immune_All_High                         immune populations combined from 20 tissues of...
            2	Adult_COVID19_PBMC                      peripheral blood mononuclear cell types from C...
            3	Adult_CynomolgusMacaque_Hippocampus 	cell types from the hippocampus of adult cynom...
            4	Adult_Human_MTG	                        cell types and subtypes (10x-based) from the a...
            5	Adult_Human_PancreaticIslet             cell types from pancreatic islets of healthy a...
            6	Adult_Human_PrefrontalCortex            cell types and subtypes from the adult human d...
            7	Adult_Human_Skin                        cell types from human healthy adult skin
            8	Adult_Human_Vascular	                vascular populations combined from multiple ad...
            9	Adult_Mouse_Gut	                        cell types in the adult mouse gut combined fro...
            10	Adult_Mouse_OlfactoryBulb               cell types from the olfactory bulb of adult mice
            11	Adult_Pig_Hippocampus	                cell types from the adult pig hippocampus
            12	Adult_RhesusMacaque_Hippocampus	        cell types from the hippocampus of adult rhesu...
            13	Autopsy_COVID19_Lung	                cell types from the lungs of 16 SARS-CoV-2 inf...
            14	COVID19_HumanChallenge_Blood	        detailed blood cell states from 16 individuals...
            15	COVID19_Immune_Landscape                immune subtypes from lung and blood of COVID-1...
            16	Cells_Adult_Breast                      cell types from the adult human breast
            17	Cells_Fetal_Lung                        cell types from human embryonic and fetal lungs
            18	Cells_Human_Tonsil                      tonsillar cell types from humans (3-65 years)
            19	Cells_Intestinal_Tract                  intestinal cells from fetal, pediatric (health...
            20	Cells_Lung_Airway                       cell populations from scRNA-seq of five locati...
            21	Developing_Human_Brain                  cell types from the first-trimester developing...
            22	Developing_Human_Gonads	                cell types of human gonadal and adjacent extra...
            23	Developing_Human_Hippocampus	        cell types from the developing human hippocampus
            24	Developing_Human_Organs	                cell types of five endoderm-derived organs in ...
            25	Developing_Human_Thymus	                cell populations in embryonic, fetal, pediatri...
            26	Developing_Mouse_Brain	                cell types from the embryonic mouse brain betw...
            27	Developing_Mouse_Hippocampus	        cell types from the mouse hippocampus at postn...
            28	Fetal_Human_AdrenalGlands               cell types of human fetal adrenal glands from ...
            29	Fetal_Human_Pancreas	                pancreatic cell types from human embryos at 9-...
            30	Fetal_Human_Pituitary	                cell types of human fetal pituitaries from 7 t...
            31	Fetal_Human_Retina                      cell types from human fetal neural retina and ...
            32	Fetal_Human_Skin                        cell types from developing human fetal skin
            33	Healthy_Adult_Heart                     cell types from eight anatomical regions of th...
            34	Healthy_COVID19_PBMC	                peripheral blood mononuclear cell types from h...
            35	Healthy_Human_Liver                     cell types from scRNA-seq and snRNA-seq of the...
            36	Healthy_Mouse_Liver                     cell types from scRNA-seq and snRNA-seq of the...
            37	Human_AdultAged_Hippocampus             cell types from the hippocampus of adult and a...
            38	Human_Colorectal_Cancer	                cell types of colon tissues from patients with...
            39	Human_Developmental_Retina              cell types from human fetal retina
            40	Human_Embryonic_YolkSac	                cell types of the human yolk sac from 4-8 post...
            41	Human_Endometrium_Atlas	                endometrial cell types integrated from seven d...
            42	Human_IPF_Lung	                        cell types from idiopathic pulmonary fibrosis,...
            43	Human_Longitudinal_Hippocampus	        cell types from the adult human anterior and p...
            44	Human_Lung_Atlas                        integrated Human Lung Cell Atlas (HLCA) combin...
            45	Human_PF_Lung	                        cell types from different forms of pulmonary f...
            46	Human_Placenta_Decidua	                cell types from first-trimester human placenta...
            47	Lethal_COVID19_Lung                     cell types from the lungs of individuals who d...
            48	Mouse_Dentate_Gyrus                     cell types from the dentate gyrus in perinatal...
            49	Mouse_Isocortex_Hippocampus             cell types from the adult mouse isocortex (neo...
            50	Mouse_Postnatal_DentateGyrus	        cell types from the mouse dentate gyrus in pos...
            51	Mouse_Whole_Brain                       cell types from the whole adult mouse brain
            52	Nuclei_Lung_Airway                      cell populations from snRNA-seq of five locati...
            53	Pan_Fetal_Human	                        stromal and immune populations from the human ...
            ''')
    )
    parser.add_argument('--model', type=str, required=True, help='Model name for annotation')
    parser.add_argument('--input', type=str, required=True, help='Path to h5ad file')
    parser.add_argument('--output', type=str, required=True, help='Path to output file')
    parser.add_argument('--mode', type=str, help='Annotation mode: best match or prob match', default='prob match', choices=['best match', 'prob match'])
    return parser.parse_args()

def main():
    args = parse_args()
    celltypist.models.download_models(model = args.model + '.pkl', force_update = False)
    model = celltypist.models.Model.load(model = args.model + '.pkl')

    # adata = sc.read(args.input)
    predictions = celltypist.annotate(args.input, model = model, majority_voting = True, mode = args.mode)
    output = predictions.predicted_labels.join(predictions.probability_matrix)

    print("\U0001F4CA Writing results to output file")
    output.to_csv(args.output, index=True)

if __name__ == '__main__':
    main()
